### ISSUE TITLE
PhySH for Atomtronics 

### ISSUE THREAD

**Issue by luigiamico** [physh-org/PhySH#24]
Dear Madames/Sirs,

with this email, we would like to suggest to include 'Atomtronics' as  a  new concept in PhySH.
Indeed, we found   17 papers submitted in 2021 and 22  submitted in 2022  published in the field   (see the attached list). In addition, a Colloquium in  Rev. Mod. Phys. 94, 041001 (2022) was recently published. Previously,  the state of the art of the field and  a roadmap article was published in AVS Quantum Sci. 3, 039201 (2021).

Yours Faithfully,
Luigi Amico.
   

[atomtronics_list.pdf](https://github.com/physh-org/PhySH/files/10899098/atomtronics_list.pdf)

**Comment by arthurpsmith** [comment]
Thanks, good suggestion, we will look into this.

**Comment by arthurpsmith** [comment]
This concept is in the new 2.6 release, which will go live later today.
