### ISSUE TITLE
PhySH for batteries

### ISSUE THREAD

**Issue by iopwsy** [physh-org/PhySH#31]
Dear author:
         I am a researcher on battery and Machine Learning, I found the `battery` exists some inappropriate level. For example, Li ploymer battery may be part of Li ion battery, or maybe better method is to use primary cell and secondary battery

**Comment by arthurpsmith** [comment]
This comment was reviewed by our editors and it was decided not to make any changes. Perhaps if a clearer description of what needs changing were provided we could look at this again. Closing for now.
